/****************************************************************/
/* MOOSE - Multiphysics Object Oriented Simulation Environment  */
/*                                                              */
/*          All contents are licensed under LGPL V2.1           */
/*             See LICENSE for full restrictions                */
/****************************************************************/

#include "ComputeCrackFrictionHeatEnergy.h"

template <>
InputParameters
validParams<ComputeCrackFrictionHeatEnergy>()
{
  InputParameters params = validParams<Material>();
  params.addParam<std::string>("base_name",
                               "Optional parameter that allows the user to define "
                               "multiple mechanics material systems on the same "
                               "block, i.e. for multiple phases");
  params.addClassDescription("Heat energy density generated by crack friction");
  params.addRequiredCoupledVar("c","Damage");
  params.addRequiredCoupledVar("dcdx","First derivative of damage with respect to x");
  params.addRequiredCoupledVar("dcdy","First derivative of damage with respect to y");
  params.addRequiredParam<Real>("friction_coefficient","crack friction coefficient");
  params.addRequiredParam<Real>("l", "Interface width");
  return params;
}

ComputeCrackFrictionHeatEnergy::ComputeCrackFrictionHeatEnergy(const InputParameters & parameters)
  : DerivativeMaterialInterface<Material>(parameters),
    _base_name(isParamValid("base_name") ? getParam<std::string>("base_name") + "_" : ""),
    _c(coupledValue("c")),
    _dcdx(coupledValue("dcdx")),
    _dcdy(coupledValue("dcdy")),
    _crack_normal(declareProperty<std::vector<Real>>("crack_normal")), // Normal to the crack surface
    _crack_normal_norm(declareProperty<Real>("crack_normal_norm")),
    _stress(getMaterialPropertyByName<RankTwoTensor>("stress")),
    _strain_rate(getMaterialPropertyByName<RankTwoTensor>("strain_rate")),
    _Jacobian_mult(getMaterialProperty<RankFourTensor>("Jacobian_mult")),
    _friction_coefficient(getParam<Real>("friction_coefficient")),
    _l(getParam<Real>("l")),
    _friction_force(declareProperty<std::vector<Real>>("friction_force")),
    _slide_velocity(declareProperty<std::vector<Real>>("slide_velocity")),
    _crack_surface_density(declareProperty<Real>("crack_surface_density")),
    _heat_source_rate(declareProperty<Real>("heat_source_rate"))
{
}

void
ComputeCrackFrictionHeatEnergy::computeQpProperties()
{

  unsigned int i, j;
  Real friction_force_dot_crack_normal = 0.0;
  Real slide_velocity_dot_crack_normal = 0.0;

  _crack_normal_norm[_qp] = std::sqrt( _dcdx[_qp]*_dcdx[_qp] + _dcdy[_qp]*_dcdy[_qp] ); // + _dcdz[_qp]*_dcdz[_qp] );

  _crack_surface_density[_qp] = 0.25*_c[_qp]*_c[_qp] + _l*_l*_crack_normal_norm[_qp]*_crack_normal_norm[_qp];

  _crack_normal[_qp].resize(2);

  if ( _crack_normal_norm[_qp] > 1.0e-9 ) {
    _crack_normal[_qp][0] = - _dcdx[_qp] / _crack_normal_norm[_qp];
    _crack_normal[_qp][1] = - _dcdy[_qp] / _crack_normal_norm[_qp];
  }
  else {
    _crack_normal[_qp][0] = 0.0;
    _crack_normal[_qp][1] = 0.0;
  }

  _friction_force[_qp].resize(2);
  _slide_velocity[_qp].resize(2);

  for( int i = 0; i < 2; i = i + 1 ) {
    _friction_force[_qp][i] = 0.0;
    _slide_velocity[_qp][i] = 0.0;
  }

  for( int i = 0; i < 2; i = i + 1 ) {
    for( int j = 0; j < 2; j = j + 1 ) {
      _friction_force[_qp][i] += _stress[_qp](i, j) * _crack_normal[_qp][j];
      _slide_velocity[_qp][i] += _strain_rate[_qp](i, j) * _crack_normal[_qp][j];
    }
  }

  for( int i = 0; i < 2; i = i + 1 ) {
    friction_force_dot_crack_normal += _friction_force[_qp][i] * _crack_normal[_qp][i];
    slide_velocity_dot_crack_normal += _slide_velocity[_qp][i] * _crack_normal[_qp][i];
  }

  _heat_source_rate[_qp] = 0.0;

  if ( friction_force_dot_crack_normal < 0.0 && slide_velocity_dot_crack_normal < 0.0 ) {
    for( int i = 0; i < 2; i = i + 1 ) {
      _heat_source_rate[_qp] += _friction_coefficient * (_friction_force[_qp][i] * _slide_velocity[_qp][i]);
    }
    _heat_source_rate[_qp] *= _crack_surface_density[_qp];
  }

}
